config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
   
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("ubold.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("apps/", include("ubold.apps.urls", namespace="apps"),),
    path("layouts/", include("ubold.layouts.urls", namespace="layouts"),),
    path("pages/", include("ubold.pages.urls", namespace="pages"),),
    path("components/", include("ubold.components.urls", namespace="components"),),
    path("accounts/", include("ubold.accounts.urls", namespace="accounts"),),
    path("dashboard/", include("ubold.dashboard.urls", namespace="dashboard"),),
    path("", TemplateView.as_view(template_name="landing.html"), name="landing"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ubold/apps/urls.py
from django.urls import path

from .views import (
    apps_calendar_calendar_view,
    apps_chat_chat_view,

    apps_companies_view,

    apps_ecommerce_ecommerce_dashboard_view,

    apps_ecommerce_checkout_view,
    apps_ecommerce_customers_view,
    apps_ecommerce_order_detail_view,
    apps_ecommerce_orders_view,
    apps_ecommerce_product_edit_view,
    apps_ecommerce_products_details_view,
    apps_ecommerce_products_view,
    apps_ecommerce_sellers_view,
    apps_ecommerce_cart_view,

    apps_crm_dashboard_view,
    apps_crm_contacts_view,
    apps_crm_opportunities_view,
    apps_crm_leads_view,
    apps_crm_customers_view,

    apps_contacts_list_view,
    apps_contacts_profile_view,

    apps_file_manager_view,

    apps_email_inbox_view,
    apps_email_read_view,
    apps_email_compose_view,
    apps_email_templates_view,
    apps_email_templates_action_view,
    apps_email_templates_alert_view,
    apps_email_templates_billing_view,


    apps_project_create_view,
    apps_project_detail_view,
    apps_project_list_view,

    apps_social_feed_view,

    apps_task_details_view,
    apps_task_kanban_board_view,
    apps_task_list_view,

    apps_tickets_list_view,
    apps_tickets_detail_view,

    # event
    EventListView,
    EventCreateView,
    EventUpdateView,
    EventDeleteView,

)


app_name = "apps"
urlpatterns = [
    # calendar
    path("event/", view=EventListView.as_view(), name="event-list"),
    path("event/add/", view=EventCreateView.as_view(), name="event-add"),
    path("event/edit/<pk>", view=EventUpdateView.as_view(), name="event-edit"),
    path("event/remove/<pk>", view=EventDeleteView.as_view(), name="event-remove"),
    path("calendar", view=apps_calendar_calendar_view, name="calendar"),

    # chat
    path("chat", view=apps_chat_chat_view, name="chat"),

    # crm
    path("crm/customers", view=apps_crm_customers_view, name="crm.customers"),
    path("crm/contacts", view=apps_crm_contacts_view, name="crm.contacts"),
    path("crm/dashboard", view=apps_crm_dashboard_view, name="crm.dashboard"),
    path("crm/leads", view=apps_crm_leads_view, name="crm.leads"),
    path("crm/opportunities", view=apps_crm_opportunities_view, name="crm.opportunities"),

    # companies
    path("companies/companies", view=apps_companies_view, name="companies.companies"),

    # contacts
    path("contacts/list", view=apps_contacts_list_view, name="contacts.list"),
    path("contacts/profile", view=apps_contacts_profile_view, name="contacts.profile"),

    # ecommerce
    path("ecommerce/checkout", view=apps_ecommerce_checkout_view, name="ecommerce.checkout"),
    path("ecommerce/customers", view=apps_ecommerce_customers_view, name="ecommerce.customers"),
    path("ecommerce/dashboard",
         view=apps_ecommerce_ecommerce_dashboard_view, name="ecommerce.dashboard"),
    path("ecommerce/order-detail", view=apps_ecommerce_order_detail_view,
         name="ecommerce.order-detail"),
    path("ecommerce/orders", view=apps_ecommerce_orders_view, name="ecommerce.orders"),
    path("ecommerce/product-edit", view=apps_ecommerce_product_edit_view, name="ecommerce.product-edit"),
    path("ecommerce/product-detail", view=apps_ecommerce_products_details_view,
         name="ecommerce.product-detail"),
    path("ecommerce/products", view=apps_ecommerce_products_view, name="ecommerce.products"),
    path("ecommerce/sellers", view=apps_ecommerce_sellers_view, name="ecommerce.sellers"),
    path("ecommerce/cart", view=apps_ecommerce_cart_view,
         name="ecommerce.cart"),

    # email
    path("email/inbox", view=apps_email_inbox_view, name="email.inbox"),
    path("email/read", view=apps_email_read_view, name="email.read"),
    path("email/compose", view=apps_email_compose_view, name="email.compose"),
    path("email/templates", view=apps_email_templates_view, name="email.templates"),
    path("email/templates-action", view=apps_email_templates_action_view, name="email.templates-action"),
    path("email/templates-alert", view=apps_email_templates_alert_view, name="email.templates-alert"),
    path("email/templates-billing", view=apps_email_templates_billing_view,
         name="email.templates-billing"),

    # manager
    path("manager/file-manager", view=apps_file_manager_view, name="manager.file-manager"),

    # projects //TODO
    path("project/create", view=apps_project_create_view, name="project.create"),
    path("project/detail", view=apps_project_detail_view, name="project.detail"),
    path("project/list", view=apps_project_list_view, name="project.list"),

    # social
    path("social/feed", view=apps_social_feed_view, name="social.feed"),

    # tasks
    path("task/details", view=apps_task_details_view, name="task.details"),
    path("task/kanban-board", view=apps_task_kanban_board_view, name="task.kanban-board"),
    path("task/list", view=apps_task_list_view, name="task.list"),

    # tickets
    path("tickets/list", view=apps_tickets_list_view, name="tickets.list"),
    path("tickets/detail", view=apps_tickets_detail_view, name="tickets.detail"),

]

ubold/pages/urls.py
from django.urls import path

from .views import (

    custom_pages_coming_soon_view,
    custom_pages_faqs_view,
    custom_pages_gallery_view,
    custom_pages_invoice_view,
    custom_pages_maintenance_view,
    custom_pages_pricing_view,
    custom_pages_search_results_view,
    custom_pages_sitemap_view,
    custom_pages_starter_view,
    custom_pages_timeline_view,
    custom_pages_404_alt_view,
    custom_pages_404_two_view,
    custom_pages_404_view,
    custom_pages_500_two_view,
    custom_pages_500_view,
)


app_name = "pages"
urlpatterns = [

    # pages
    path("coming-soon", view=custom_pages_coming_soon_view, name="coming-soon"),
    path("faqs", view=custom_pages_faqs_view, name="faqs"),
    path("gallery", view=custom_pages_gallery_view, name="gallery"),
    path("invoice", view=custom_pages_invoice_view, name="invoice"),
    path("maintenance", view=custom_pages_maintenance_view, name="maintenance"),
    path("pricing", view=custom_pages_pricing_view, name="pricing"),
    path("search-results", view=custom_pages_search_results_view, name="search-results"),
    path("sitemap", view=custom_pages_sitemap_view, name="sitemap"),
    path("starter", view=custom_pages_starter_view, name="starter"),
    path("timeline", view=custom_pages_timeline_view, name="timeline"),
    path("404-alt", view=custom_pages_404_alt_view, name="404-alt"),
    path("404-two", view=custom_pages_404_two_view, name="404-two"),
    path("404", view=custom_pages_404_view, name="404"),
    path("500", view=custom_pages_500_view, name="500"),
    path("500-two", view=custom_pages_500_two_view, name="500-two"),
]

ubold/users/urls.py
from django.urls import path

from ubold.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

ubold/accounts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import TemplateView

User = get_user_model()

class AccountsView(LoginRequiredMixin, TemplateView):
    pass

#auth pages
auth_pages_confirm_email_view = AccountsView.as_view(template_name="auth/confirm-email.html")
auth_pages_confirm_email_2_view = AccountsView.as_view(template_name="auth/confirm-email-2.html")

auth_pages_login_2_view = AccountsView.as_view(template_name="auth/login-2.html")
auth_pages_logout_view = AccountsView.as_view(template_name="auth/logout.html")
auth_pages_logout_2_view = AccountsView.as_view(template_name="auth/logout-2.html")

auth_pages_lock_screen_view = AccountsView.as_view(template_name="auth/lock-screen.html")
auth_pages_lock_screen_2_view = AccountsView.as_view(template_name="auth/lock-screen-2.html")


auth_pages_recoverpw_view = AccountsView.as_view(template_name="auth/recoverpw.html")
auth_pages_recoverpw_2_view = AccountsView.as_view(template_name="auth/recoverpw-2.html")
auth_pages_register_2_view = AccountsView.as_view(template_name="auth/register-2.html")

auth_pages_signin_signup_view = AccountsView.as_view(template_name="auth/signin-signup.html")
auth_pages_signin_signup_2_view = AccountsView.as_view(template_name="auth/signin-signup-2.html")

ubold/components/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import TemplateView

User = get_user_model()

class ComponentsView(LoginRequiredMixin, TemplateView):
    pass

# ecommerce
components_base_ui_tabs_accordions_view = ComponentsView.as_view(template_name="components/base-ui/tabs-accordions.html")
components_base_ui_avatars_view = ComponentsView.as_view(template_name="components/base-ui/avatars.html")
components_base_ui_buttons_view = ComponentsView.as_view(template_name="components/base-ui/buttons.html")
components_base_ui_cards_view = ComponentsView.as_view(template_name="components/base-ui/cards.html")
components_base_ui_carousel_view = ComponentsView.as_view(template_name="components/base-ui/carousel.html")
components_base_ui_dropdowns_view = ComponentsView.as_view(template_name="components/base-ui/dropdowns.html")
components_base_ui_video_view = ComponentsView.as_view(template_name="components/base-ui/video.html")
components_base_ui_general_view = ComponentsView.as_view(template_name="components/base-ui/general.html")
components_base_ui_grid_view = ComponentsView.as_view(template_name="components/base-ui/grid.html")
components_base_ui_images_view = ComponentsView.as_view(template_name="components/base-ui/images.html")
components_base_ui_list_group_view = ComponentsView.as_view(template_name="components/base-ui/list-group.html")
components_base_ui_modals_view = ComponentsView.as_view(template_name="components/base-ui/modals.html")
components_base_ui_notifications_view = ComponentsView.as_view(template_name="components/base-ui/notifications.html")
components_base_ui_tooltips_popovers_view = ComponentsView.as_view(template_name="components/base-ui/tooltips-popovers.html")
components_base_ui_portlets_view = ComponentsView.as_view(template_name="components/base-ui/portlets.html")
components_base_ui_progress_view = ComponentsView.as_view(template_name="components/base-ui/progress.html")
components_base_ui_ribbons_view = ComponentsView.as_view(template_name="components/base-ui/ribbons.html")
components_base_ui_spinners_view = ComponentsView.as_view(template_name="components/base-ui/spinners.html")
components_base_ui_typography_view = ComponentsView.as_view(template_name="components/base-ui/typography.html")
components_base_ui_offcanvas_view = ComponentsView.as_view(template_name="components/base-ui/offcanvas.html")


# extended
components_extended_dragula_view = ComponentsView.as_view(template_name="components/extended/dragula.html")
components_extended_nestable_view = ComponentsView.as_view(template_name="components/extended/nestable.html")
components_extended_range_slider_view = ComponentsView.as_view(template_name="components/extended/range-slider.html")
components_extended_animation_view = ComponentsView.as_view(template_name="components/extended/animation.html")
components_extended_sweet_alert_view = ComponentsView.as_view(template_name="components/extended/sweet-alert.html")
components_extended_tour_view = ComponentsView.as_view(template_name="components/extended/tour.html")
components_extended_scrollspy_view = ComponentsView.as_view(template_name="components/extended/scrollspy.html")
components_extended_loading_buttons_view = ComponentsView.as_view(template_name="components/extended/loading-buttons.html")

# widgets
components_widgets_view = ComponentsView.as_view(template_name="components/widgets.html")

# icons
components_icons_two_tone_view = ComponentsView.as_view(template_name="components/icons/two-tone.html")
components_icons_feather_view = ComponentsView.as_view(template_name="components/icons/feather.html")
components_icons_mdi_view = ComponentsView.as_view(template_name="components/icons/mdi.html")
components_icons_dripicons_view = ComponentsView.as_view(template_name="components/icons/dripicons.html")
components_icons_font_awesome_view = ComponentsView.as_view(template_name="components/icons/font-awesome.html")
components_icons_themify_view = ComponentsView.as_view(template_name="components/icons/themify.html")
components_icons_simple_line_view = ComponentsView.as_view(template_name="components/icons/simple-line.html")
components_icons_weather_view = ComponentsView.as_view(template_name="components/icons/weather.html")

# forms
components_forms_elements_view = ComponentsView.as_view(template_name="components/forms/elements.html")
components_forms_advanced_view = ComponentsView.as_view(template_name="components/forms/advanced.html")
components_forms_validation_view = ComponentsView.as_view(template_name="components/forms/validation.html")
components_forms_pickers_view = ComponentsView.as_view(template_name="components/forms/pickers.html")
components_forms_wizard_view = ComponentsView.as_view(template_name="components/forms/wizard.html")
components_forms_masks_view = ComponentsView.as_view(template_name="components/forms/masks.html")
components_forms_quilljs_view = ComponentsView.as_view(template_name="components/forms/quilljs.html")
components_forms_file_uploads_view = ComponentsView.as_view(template_name="components/forms/file-uploads.html")
components_forms_x_editable_view = ComponentsView.as_view(template_name="components/forms/x-editable.html")
components_forms_image_crop_view = ComponentsView.as_view(template_name="components/forms/image-crop.html")



# charts
components_charts_apex_view = ComponentsView.as_view(template_name="components/charts/apex.html")
components_charts_flot_view = ComponentsView.as_view(template_name="components/charts/flot.html")
components_charts_morris_view = ComponentsView.as_view(template_name="components/charts/morris.html")
components_charts_chartjs_view = ComponentsView.as_view(template_name="components/charts/chartjs.html")
components_charts_peity_view = ComponentsView.as_view(template_name="components/charts/peity.html")
components_charts_chartist_view = ComponentsView.as_view(template_name="components/charts/chartist.html")
components_charts_c3_view = ComponentsView.as_view(template_name="components/charts/c3.html")
components_charts_sparklines_view = ComponentsView.as_view(template_name="components/charts/sparklines.html")
components_charts_knob_view = ComponentsView.as_view(template_name="components/charts/knob.html")


# tables
components_tables_basic_view = ComponentsView.as_view(template_name="components/tables/basic.html")
components_tables_datatables_view = ComponentsView.as_view(template_name="components/tables/datatables.html")
components_tables_editable_view = ComponentsView.as_view(template_name="components/tables/editable.html")
components_tables_responsive_view = ComponentsView.as_view(template_name="components/tables/responsive.html")
components_tables_footables_view = ComponentsView.as_view(template_name="components/tables/footables.html")
components_tables_bootstrap_view = ComponentsView.as_view(template_name="components/tables/bootstrap.html")
components_tables_tablesaw_view = ComponentsView.as_view(template_name="components/tables/tablesaw.html")
components_tables_jsgrid_view = ComponentsView.as_view(template_name="components/tables/jsgrid.html")

# maps
components_maps_google_view = ComponentsView.as_view(template_name="components/maps/google.html")
components_maps_vector_view = ComponentsView.as_view(template_name="components/maps/vector.html")
components_maps_mapael_view = ComponentsView.as_view(template_name="components/maps/mapael.html")

ubold/templates/apps/calendar/calendar.html
{% extends "vertical_base.html" %}
{% load static i18n %}

{% block head_title %}{% trans "Calendar" %}{% endblock head_title %}

{% block extra_css %}

<!-- third party css -->
<link href="{% static 'libs/fullcalendar/main.min.css' %}" rel="stylesheet" type="text/css" />
<!-- third party css end -->

{% endblock %}

{% block content %}
<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Apps</a></li>
                        <li class="breadcrumb-item active">Calendar</li>
                    </ol>
                </div>
                <h4 class="page-title">Calendar</h4>
            </div>
        </div>
    </div>     
    <!-- end page title --> 

    <div class="row">
        <div class="col-12">
            <div id="eventurls" class="d-none" data-list="{% url 'apps:event-list' %}"
                data-add="{% url 'apps:event-add' %}">
            </div>
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-3">
                            <button class="btn btn-lg font-16 btn-primary w-100" id="btn-new-event"><i class="mdi mdi-plus-circle-outline"></i> Create New Event</button>
                            
                            <div id="external-events">
                                <br>
                                <p class="text-muted">Drag and drop your event or click in the calendar</p>
                                <div class="external-event bg-success" data-class="bg-success">
                                    <i class="mdi mdi-checkbox-blank-circle me-2 vertical-middle"></i>New Theme Release
                                </div>
                                <div class="external-event bg-info" data-class="bg-info">
                                    <i class="mdi mdi-checkbox-blank-circle me-2 vertical-middle"></i>My Event
                                </div>
                                <div class="external-event bg-warning" data-class="bg-warning">
                                    <i class="mdi mdi-checkbox-blank-circle me-2 vertical-middle"></i>Meet manager
                                </div>
                                <div class="external-event bg-danger" data-class="bg-danger">
                                    <i class="mdi mdi-checkbox-blank-circle me-2 vertical-middle"></i>Create New theme
                                </div>
                            </div>


                            <div class="mt-5 d-none d-xl-block">
                                <h5 class="text-center">How It Works ?</h5>

                                <ul class="ps-3">
                                    <li class="text-muted mb-3">
                                        It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
                                    </li>
                                    <li class="text-muted mb-3">
                                        Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage.
                                    </li>
                                    <li class="text-muted mb-3">
                                        It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
                                    </li>
                                </ul>
                            </div>

                        </div> <!-- end col-->

                        <div class="col-lg-9">
                            <div id="calendar"></div>
                        </div> <!-- end col -->

                    </div>  <!-- end row -->
                </div> <!-- end card body-->
            </div> <!-- end card -->

            <!-- Add New Event MODAL -->
            <div class="modal fade" id="event-modal" tabindex="-1">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header py-3 px-4 border-bottom-0 d-block">
                            <button type="button" class="btn-close float-end" data-bs-dismiss="modal" aria-label="Close"></button>
                            <h5 class="modal-title" id="modal-title">Event</h5>
                        </div>
                        <div class="modal-body px-4 pb-4 pt-0">
                            <form class="needs-validation" name="event-form" id="form-event" novalidate>
                                {% csrf_token %}
                                <div class="row">
                                                <div class="col-12">
                                                    <div class="mb-3">
                                                        <label class="form-label">Event Name</label>
                                                        <input class="form-control" placeholder="Insert Event Name"
                                                            type="text" name="title" id="event-title" required />
                                                        <div class="invalid-feedback">Please provide a valid event name
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-12">
                                                    <div class="mb-3">
                                                        <label class="form-label">Category</label>
                                                        <select class="form-select" name="category" id="event-category"
                                                            required>
                                                            <option value="bg-danger" selected>Danger</option>
                                                            <option value="bg-success">Success</option>
                                                            <option value="bg-primary">Primary</option>
                                                            <option value="bg-info">Info</option>
                                                            <option value="bg-dark">Dark</option>
                                                            <option value="bg-warning">Warning</option>
                                                        </select>
                                                        <div class="invalid-feedback">Please select a valid event
                                                            category</div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row mt-2">
                                                <div class="col-md-6 col-4">
                                                    <button type="button" class="btn btn-danger"
                                                        id="btn-delete-event">Delete</button>
                                                </div>
                                                <div class="col-md-6 col-8 text-end">
                                                    <button type="button" class="btn btn-light me-1"
                                                        data-bs-dismiss="modal">Close</button>
                                                    <button type="submit" class="btn btn-success"
                                                        id="btn-save-event">Save</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div> <!-- end modal-content-->
                            </div> <!-- end modal dialog-->
                        </div>
                        <!-- end modal-->
                    </div>
                    <!-- end col-12 -->
                </div> <!-- end row -->

            </div> <!-- container -->

        </div> <!-- content -->
{% endblock %}

{% block extra_javascript %}

<!-- Third party js -->
<script src="{% static 'libs/moment/min/moment.min.js' %}"></script>
<script src="{% static 'libs/fullcalendar/main.min.js' %}"></script>
<!-- Third party js ends -->

<!-- Init js -->
<script src="{% static 'js/pages/calendar.init.js' %}"></script>
<!-- Init js end -->

{% endblock %}